use std::fmt;
use std::time::Duration;

use tokio::sync::oneshot;

use crate::process::ExitReason;

/// Callback mode for the state machine.
///
/// Determines how events are dispatched to the callback implementation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CallbackMode {
    /// All events route through a single `handle_event` callback.
    /// The current state is passed as a parameter.
    HandleEventFunction,
}

/// Event types that the state machine handles.
///
/// Each variant describes the origin of an event, allowing the
/// `handle_event` callback to distinguish between calls, casts,
/// timeouts, and internal events.
#[derive(Debug)]
pub enum EventType<Reply> {
    /// Synchronous call (expects a reply via the contained sender).
    Call(oneshot::Sender<Reply>),
    /// Asynchronous cast (fire-and-forget).
    Cast,
    /// Raw info message from the mailbox.
    Info,
    /// State timeout expired (cancelled on state change).
    StateTimeout,
    /// Generic named timeout expired.
    Timeout(String),
    /// Event timeout expired (cancelled on any external event).
    EventTimeout,
    /// Internal event (generated by a `NextEvent` action).
    Internal,
    /// State enter event, carrying the name of the previous state.
    Enter {
        /// Debug representation of the previous state.
        old_state_name: String,
    },
}

/// Actions the state machine can take during a transition.
///
/// Actions are returned as part of a [`TransitionResult`] and are
/// processed after the state transition completes.
pub enum Action<State, Reply> {
    /// Send a reply to a caller.
    Reply(oneshot::Sender<Reply>, Reply),
    /// Set a state timeout (cancelled on state change).
    StateTimeout(Duration, rmpv::Value),
    /// Set an event timeout (cancelled on any external event).
    EventTimeout(Duration, rmpv::Value),
    /// Set a named generic timeout (independent, per-name).
    GenericTimeout(String, Duration, rmpv::Value),
    /// Cancel a specific timeout.
    CancelTimeout(TimeoutKind),
    /// Postpone the current event (re-queue on state change).
    Postpone,
    /// Insert an internal event into the front of the queue.
    NextEvent(rmpv::Value),
    /// Hibernate hint (accepted but no-op in tokio).
    Hibernate,
    /// Marker to suppress `missing_debug_implementations` on `State`.
    #[doc(hidden)]
    _Phantom(std::marker::PhantomData<State>),
}

// Manual Debug because State may not implement Debug in all positions,
// and oneshot::Sender doesn't implement Debug.
impl<State, Reply> fmt::Debug for Action<State, Reply> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Reply(_, _) => f.write_str("Action::Reply(..)"),
            Self::StateTimeout(d, v) => {
                f.debug_tuple("Action::StateTimeout").field(d).field(v).finish()
            }
            Self::EventTimeout(d, v) => {
                f.debug_tuple("Action::EventTimeout").field(d).field(v).finish()
            }
            Self::GenericTimeout(name, d, v) => f
                .debug_tuple("Action::GenericTimeout")
                .field(name)
                .field(d)
                .field(v)
                .finish(),
            Self::CancelTimeout(k) => f.debug_tuple("Action::CancelTimeout").field(k).finish(),
            Self::Postpone => f.write_str("Action::Postpone"),
            Self::NextEvent(v) => f.debug_tuple("Action::NextEvent").field(v).finish(),
            Self::Hibernate => f.write_str("Action::Hibernate"),
            Self::_Phantom(_) => f.write_str("Action::_Phantom"),
        }
    }
}

/// Identifies which timeout to cancel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TimeoutKind {
    /// Cancel the state timeout.
    State,
    /// Cancel the event timeout.
    Event,
    /// Cancel a named generic timeout.
    Generic(String),
}

/// Result of handling an event in the state machine.
///
/// Determines the next state, data, and any actions to execute.
pub enum TransitionResult<State, Data, Reply> {
    /// Transition to a new state with new data.
    NextState {
        /// The new state to transition to.
        state: State,
        /// The updated data.
        data: Data,
        /// Actions to execute after the transition.
        actions: Vec<Action<State, Reply>>,
    },
    /// Keep the current state, update data.
    KeepState {
        /// The updated data.
        data: Data,
        /// Actions to execute.
        actions: Vec<Action<State, Reply>>,
    },
    /// Keep state and data unchanged, optionally with actions.
    KeepStateAndData {
        /// Actions to execute.
        actions: Vec<Action<State, Reply>>,
    },
    /// Stop the state machine.
    Stop {
        /// The reason for stopping.
        reason: ExitReason,
        /// The final data.
        data: Data,
    },
    /// Stop with pending replies sent before shutdown.
    StopAndReply {
        /// The reason for stopping.
        reason: ExitReason,
        /// The final data.
        data: Data,
        /// Replies to send before shutting down.
        replies: Vec<(oneshot::Sender<Reply>, Reply)>,
    },
}

// Manual Debug to avoid requiring Debug on all type parameters.
impl<State: fmt::Debug, Data, Reply> fmt::Debug for TransitionResult<State, Data, Reply> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NextState { state, actions, .. } => f
                .debug_struct("NextState")
                .field("state", state)
                .field("actions_count", &actions.len())
                .finish(),
            Self::KeepState { actions, .. } => f
                .debug_struct("KeepState")
                .field("actions_count", &actions.len())
                .finish(),
            Self::KeepStateAndData { actions } => f
                .debug_struct("KeepStateAndData")
                .field("actions_count", &actions.len())
                .finish(),
            Self::Stop { reason, .. } => {
                f.debug_struct("Stop").field("reason", reason).finish()
            }
            Self::StopAndReply { reason, replies, .. } => f
                .debug_struct("StopAndReply")
                .field("reason", reason)
                .field("replies_count", &replies.len())
                .finish(),
        }
    }
}

/// The `GenStatem` trait. Implement this for your state machine.
///
/// Associated types define the state machine's protocol:
/// - `State`: the set of states (typically an enum)
/// - `Data`: mutable data carried across states
/// - `Call`: synchronous request message type
/// - `Cast`: asynchronous fire-and-forget message type
/// - `Reply`: response type for calls
#[async_trait::async_trait]
pub trait GenStatem: Send + Sync + 'static {
    /// The state type. Each variant represents a distinct state.
    type State: Send + Clone + PartialEq + fmt::Debug + 'static;
    /// Mutable data carried across states.
    type Data: Send + 'static;
    /// Synchronous call message type.
    type Call: Send + 'static;
    /// Asynchronous cast message type.
    type Cast: Send + 'static;
    /// Reply type for calls.
    type Reply: Send + 'static;

    /// Return the callback mode and whether state enter callbacks are enabled.
    ///
    /// When the second element is `true`, `handle_event` will be called with
    /// `EventType::Enter` on every state change.
    fn callback_mode(&self) -> (CallbackMode, bool);

    /// Initialize the state machine. Returns the initial `(state, data)`.
    ///
    /// # Errors
    ///
    /// Returns a `String` describing the initialization failure.
    async fn init(&self) -> Result<(Self::State, Self::Data), String>;

    /// Handle all events. Dispatched based on the current state and event type.
    async fn handle_event(
        &self,
        event_type: EventType<Self::Reply>,
        event: rmpv::Value,
        state: &Self::State,
        data: &mut Self::Data,
    ) -> TransitionResult<Self::State, Self::Data, Self::Reply>;

    /// Called when the state machine is shutting down.
    ///
    /// Default implementation does nothing.
    #[allow(clippy::unused_async)]
    async fn terminate(
        &self,
        _reason: ExitReason,
        _state: &Self::State,
        _data: &mut Self::Data,
    ) {
    }
}
